services:
  # PostgreSQL資料庫
  postgres:
    image: postgres:15
    container_name: paper_analysis_db
    environment:
      POSTGRES_DB: paper_analysis
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "25432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network

  # FastAPI後端
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: paper_analysis_backend
    ports:
      - "28001:8000"  # 後端 API 服務
    environment:
      - ENVIRONMENT=development
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=paper_analysis
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - GROBID_URL=${GROBID_URL}
      - N8N_BASE_URL=${N8N_BASE_URL}
      - SPLIT_SENTENCES_URL=${SPLIT_SENTENCES_URL}
      # Google OAuth 設定
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - GOOGLE_REDIRECT_URI=${GOOGLE_REDIRECT_URI}
      - FRONTEND_URL=${FRONTEND_URL}
      # JWT 和安全設定
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - JWT_ALGORITHM=${JWT_ALGORITHM}
      - JWT_EXPIRE_HOURS=${JWT_EXPIRE_HOURS}
      - SECRET_KEY=${SECRET_KEY}
    volumes:
      - ./backend:/app/backend
      - ./temp_files:/app/temp_files
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    # 添加DNS配置解決外部域名解析問題
    dns:
      - 8.8.8.8
      - 1.1.1.1
    extra_hosts:
      - "grobid.hsueh.tw:172.67.184.210"
      - "n8n.hsueh.tw:172.67.184.210"
    networks:
      - app-network

  # React前端 (開發模式)
  # react-dev:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.dev
  #   container_name: react-frontend-dev
  #   ports:
  #     - "25173:5173"
  #   volumes:
  #     - .:/app
  #     - /app/node_modules
  #   environment:
  #     - NODE_ENV=development
  #     - VITE_API_BASE_URL=http://localhost:28001/api
  #   depends_on:
  #     - backend
  #   networks:
  #     - app-network

  # React frontend service (production build)
  react:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: react-frontend
    ports:
      - "20080:80"
    environment:
      - NODE_ENV=production
      - VITE_API_BASE_URL=${VITE_API_BASE_URL:-http://localhost:28001/api}
      - VITE_WS_BASE_URL=${VITE_WS_BASE_URL:-ws://localhost:28001}
      - VITE_SPLIT_SENTENCES_BASE_URL=${VITE_SPLIT_SENTENCES_BASE_URL:-http://localhost:28000}
      - VITE_API_TIMEOUT=${VITE_API_TIMEOUT:-30000}
      - VITE_DEBUG_MODE=${VITE_DEBUG_MODE:-false}
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - app-network

  # Split Sentences API service (保留現有)
  split_sentences:
    build:
      context: ./split_sentences
      dockerfile: Dockerfile
    container_name: pdf-sentence-splitter
    ports:
      - "28000:8000"
    volumes:
      - ./split_sentences/app:/app/app
      - ./split_sentences/upload_data:/app/upload_data
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1
      - MAX_WORKERS=1
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    depends_on:
      - redis
    networks:
      - app-network

  # Redis service (required by split_sentences)
  redis:
    image: redis:alpine
    container_name: pdf-splitter-redis
    ports:
      - "26379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    networks:
      - app-network

volumes:
  postgres_data:
  redis_data:

networks:
  app-network:
    driver: bridge
